apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ytsaurus-ui-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
     {{- include "ytsaurus-ui-chart.labels" . | nindent 4 }}
data:
  clusters-config.json: |
    {{ toJson .Values.ui.clusterConfig }}
  common.js: |
    module.exports = { 
      odinBaseUrl: {{ .Values.settings.odinBaseUrl | quote }}, 
      uiSettings: {{- toJson .Values.settings.uiSettings}},
      {{- if .Values.settings.oauth.enabled }}
      ytOAuthSettings: {
        {{ range $key, $value :=  .Values.settings.oauth -}}
        {{- if or (eq $key "clientId") (eq $key "clientSecret") -}}
          {{ $key }}: process.env.{{ $value }},
        {{- else -}}
          {{ $key }}: {{ $value | quote }},
        {{- end -}}
        {{- end}}
      },
      {{ end }}
    }
